### PR TITLE
Fix font paths

### LINKED ISSUE #24: Fonts don't load properly when called by python
First things first: I don't love the way fonts are being used in this project to begin with here and it isn't clear to me we need them.

Anyway, right now the `PdfGenerator` has a `generatePdfFromScaffold` method where a bunch of fonts are registered in the `PdfPrinter` object.  The problem is is that the font paths break depending on where the script has been initiated from.

To make matters worse, `__dirname` doesn't actually exist in our current setup (this may be fixed by #20).  For now we need to do something like https://stackoverflow.com/a/32707530/159522 when defining the font paths in order to call the `mw2pdf` script from our flask app.

### PR DESCRIPTION
**Pull request by slifty**
This PR fixes the way fonts are loaded into the PDF generation script so that their paths are no longer relative to where the script is called from

Resolves #24

### CODE REVIEW

File: services/api/mw2pdf/classes/PdfGenerator.js [hunk 1]
```diff
@@ -9,6 +11,9 @@ import {
 } from 'pdf-lib'
 import { Pdf } from './Pdf.js'
 
+const __filename = fileURLToPath(import.meta.url);
+const __dirname = path.dirname(__filename);
```
Comment (hawkinsw) [inline services/api/mw2pdf/classes/PdfGenerator.js:17]: Just because I feel the need to make _some_ comment, this _could_ be simplified into one line:

`const __dirname = path.dirname(fileURLToPath(import.meta.url));`

but it's by no means necessary!

File: services/api/mw2pdf/classes/PdfGenerator.js [hunk 2]
```diff
@@ -9,6 +11,9 @@ import {
 } from 'pdf-lib'
 import { Pdf } from './Pdf.js'
 
+const __filename = fileURLToPath(import.meta.url);
```
Comment (hawkinsw) [inline services/api/mw2pdf/classes/PdfGenerator.js:16]: This _seems_ like a really cool use of the `import` syntax but I've never seen it before. Would you be willing to add a quick pointer to some documentation for the next person who, like, is an idiot?

**Review by hawkinsw — APPROVED** [review]
Just a few _optional_ items of feedback. If they are helpful, feel free to address them. If not, merge away! HTH.

File: services/api/mw2pdf/classes/PdfGenerator.js (hunk 2 above)
Comment (slifty) [reply services/api/mw2pdf/classes/PdfGenerator.js:16]: I just yoinked it from the StackOverflow that I linked to in the commit message.

I'll actually include that link in the code as well since technically stackoverflow code is licensed under CC-SA-4.0

All that said I'm hoping we can delete this after (1) switching to babel / typescript and (2) changing the way we work with fonts in the first place.

File: services/api/mw2pdf/classes/PdfGenerator.js (hunk 1 above)
Comment (slifty) [reply services/api/mw2pdf/classes/PdfGenerator.js:17]: Appreciated!

I actually prefer to optimize around code legibility rather than minimizing lines anyway so I'll keep it as is.  Plus now we have a handy __filename variable which I'm *SURE* will be useful...  😂
